# use the official gcc image, based on debian
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  before_script:
    - echo 'deb http://apt.llvm.org/jessie/ llvm-toolchain-jessie-3.9 main' >> /etc/apt/sources.list.d/llvm.list
    - echo 'deb-src http://apt.llvm.org/jessie/ llvm-toolchain-jessie-3.9 main' >> /etc/apt/sources.list.d/llvm.list
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
    - apt update && apt -y install cmake re2c lemon clang-3.9 libllvm3.9 llvm-3.9-dev llvm-3.9-runtime
  script:
    - sh -c "mkdir -p build; cd build; cmake ..;"
    - sh -c "cd build; make;"
  artifacts:
    paths:
      - build/bp_jit

test:
  stage: test
  script:
    - bash scripts/tests/test_jit.sh
