language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - cmake
      - clang-3.9
      - llvm-3.9-dev
      - llvm-3.9-runtime
      - re2c
      - lemon
      - cloc
      - valgrind

install:
  - bash scripts/install_local_lemon.sh
  - export PATH="${HOME}/.local/bin:$PATH"

script:
  - sh -c "mkdir -p build; cd build; cmake ..; make -j3"
  - bash scripts/tests/test_fine_errors.sh
  - bash scripts/tests/test_valgrind.sh

after_success: bash scripts/print_stats.sh
