language: cpp

dist: trusty

install:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake clang-3.9 llvm-3.9-dev llvm-3.9-runtime re2c lemon cloc
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/s/sqlite3/lemon_3.14.1-1build1_amd64.deb
  - sudo dpkg -i lemon_3.14.1-1build1_amd64.deb

script:
  - mkdir build
  - sh -c "cd build; cmake ..; make"
  - bash scripts/tests/test_jit.sh
  - bash scripts/tests/test_errors.sh

after_success:
  - cloc "$TRAVIS_BUILD_DIR/src"