language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - cmake
      - clang-3.9
      - llvm-3.9-dev
      - llvm-3.9-runtime
      - re2c
      - lemon
      - cloc

install:
  - ./scripts/install_local_lemon.sh
  - export PATH="${HOME}/.local/bin:$PATH"

before_script:
  - mkdir build

script:
  - sh -c "cd build; cmake ..; make -j3"
  - bash scripts/tests/test_jit.sh
  - bash scripts/tests/test_errors.sh

after_success:
  - cloc "$TRAVIS_BUILD_DIR/src"
  - sh -c 'cd "$TRAVIS_BUILD_DIR/src" wc -l $(find examples/ -name '*.bp' | sort)'
  - sh -c 'cd "$TRAVIS_BUILD_DIR/src" wc -l $(find scripts/tests/ -name '*.bp' | sort)'
